### ISSUE TITLE
코드 질문 드립니다

### ISSUE THREAD

**Issue by nanikit** [sokcuri/ehnd#1]
[여기](https://github.com/sokcuri/ehnd/blob/a2c6e0fbb309690b440a2e65027076b67e1cd3a2/ehnd/hook.cpp#L499)에 인자를 전달해주기만 하는 것 같은데 어셈블리 코드가 들어가서 어떤 의도가 있었는지 궁금해서 질문드립니다.

그리고 타래는 어떻게 되어가나요..?

**Comment by sokcuri** [comment]
안녕하세요. 해당 코드는 아랄트랜스에서 WideCharToMultiByte와 MultiByteToWideChar를 후킹하게 되면서 비정상 작동하는 문제가 있었는데 원 함수를 어셈블리로 참조하는 방어 코드입니다.

그리고 타래는 천천히 개발중입니다. 관심을 가져 주셔서 감사합니다

**Comment by nanikit** [comment]
네 답변 고맙습니다!
